name: PR Checks

# We don't run these jobs on pull requests because:
# 1. it is often useful to run tests on one's branch without creating a pull
#    request, and
# 2. running on both pushes and pull requests results in the classic problem of
#    having double jobs.
on: push

# Left to-do:
# - coverage
# - publishing docs to gh-pages
# - persistent artifact cache
# - overnight jobs
# - other one-off jobs like missing-deps, plugin jobs etc
# - wsl tasks (TODO: Check if GitHub's Windows runners allow WSL)
#
# New opportunities:
# - run tests on mac (GitHub provides MacOS runners)
# - standardize WSL tasks by using GitHub-provided runners

env:
  BUILDBOX_VERSION: 0.0.14
  CI_IMAGE: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-154893333
  PYTEST_ARGS: --color=yes --integration -n 4

jobs:

  tests-mac:
    runs-on: macos-10.15
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        # BuildStream requires tags to be able to find its version.
        with:
          fetch-depth: 0
      - name: Install buildbox-common
        run: |
          brew install cmake protobuf grpc openssl pkgconfig
          git clone --branch $BUILDBOX_VERSION --depth 1 https://gitlab.com/BuildGrid/buildbox/buildbox-common.git
          cd buildbox-common
          cmake -DBUILD_TESTING=OFF -Bbuild -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
          make -C build
          make -C build install
      - name: Install buildbox-casd
        run: |
          git clone --branch $BUILDBOX_VERSION --depth 1 https://gitlab.com/BuildGrid/buildbox/buildbox-casd.git
          cd buildbox-casd
          cmake -DBUILD_TESTING=OFF -Bbuild -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
          make -C build
          make -C build install
      - name: Install tox
        run: pip3 install tox
      - name: Run non-integration tests
        run: tox -- --color=yes --timeout=100
